version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: MaxMarket_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: maxmarket_user
      POSTGRES_PASSWORD: maxmarket_password
      POSTGRES_DB: maxmarket_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
